config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  resources :books
  resources :movies
  root 'home#index'
end

app/models/itune.rb
class Itune < ActiveRecord::Base
  def self.search(term)
  url = URI("https://itunes.apple.com/search?term=#{URI.encode(term)}&entity=song&limit=10&sort=recent")
    response = JSON.parse(Net::HTTP.get(url))
    response["results"].map do |track|
      { trackName: track["trackName"], 
        trackId: track["trackId"], 
        artworkUrl60: track["artworkUrl60"],
        previewUrl: track["previewUrl"] }
    end
  end

  def self.lookup(isbn)
  url = URI("https://itunes.apple.com/lookup?isbn=#{URI.encode(isbn)}")
    response = JSON.parse(Net::HTTP.get(url))
    response["results"].map do |book|
      { artworkUrl100: book["artworkUrl100"],
        trackName: book["trackName"],
        trackViewUrl: book["trackViewUrl"]}
    end
  end

  def self.find(actor)
  url = URI("https://itunes.apple.com/search?term=#{URI.encode(actor)}&media=movie&limit=5&sort=recent")
    response = JSON.parse(Net::HTTP.get(url))
    response["results"].map do |movie|
      { artworkUrl100: movie["artworkUrl100"],
        trackName: movie["trackName"],
        trackViewUrl: movie["trackViewUrl"]}
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Itune.lookup(params[:q] || "9780062073501")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Itune.find(params[:q] || "leonardo di caprio")
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    @tracks = Itune.search(params[:q] || "adele")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/books/index.html.erb
<div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <h4>iBook Lookup - Search by 13 digit ISBN Number <br>(*no dashes)</h4>

      <%= form_tag books_path, method: :get do %>
        <%= text_field_tag :q %>
      <br>
        <button class="btn waves-effect waves-light" type="submit" name="action">
          <%= submit_tag "search" %>
        </button>
      <% end %>

      <br>

      <h5>You may test this app by using one of the following ISBN numbers below:

      <ul>
        <strong>
          <li>9780316069359</li>
          <li>9781443419789</li>
          <li>9780062073501</li>
        </strong>
      <ul>
      
      </h5>

      <hr>

      <h5> Result for ISBN <%= params[:q] || "9780062073501" %></h5>

      <ul>
        <% for book in @books %>
        <li><%= image_tag book[:artworkUrl100] %></li>
        <li><%= book[:trackName] %></li>
        <li><a href="<%= book[:trackViewUrl] %>" target="_blank">View In Itunes</a></li>
        <% end %>
      </ul>

    </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="section">

      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <a href="/tracks"><h2 class="center light-blue-text"><i class="material-icons">library_music</i></h2></a>
            <h5 class="center"> For Music Lovers</h5>

            <p class="light">View a list of 10 recent songs by searching your favorite artist's name. By default, you can see an example of Adele's song list. It even features a preview of the audio.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <a href="/books"><h2 class="center light-blue-text"><i class="material-icons">library_books</i></h2></a>
            <h5 class="center">For Book Worms</h5>

            <p class="light">View a book available in the Itunes Library by searching the 13 digit ISBN number. Test my suggestions by pasting its number in the search box.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <a href="/movies"><h2 class="center light-blue-text"><i class="material-icons">videocam</i></h2></a>
            <h5 class="center">For Movie Buffs</h5>

            <p class="light">In honor of Leonardo Di Caprio's Oscar win, I featured a list of his 5 recent movies. Not into Leo? Search your favorite actor or actress instead.</p>
          </div>
        </div>
      </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>

  <title>Itunes</title>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">ITUNES API</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        <li><a href="/tracks">Tracks</a></li>
        <li><a href="/books">Books</a></li>
        <li><a href="/movies">Movies</a></li>
      </ul>
    </div>
  </nav>

<%= yield %>

  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/movies/index.html.erb
<div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <h4>5 Recent Movies - Search by Actor's Name</h4>

      <%= form_tag movies_path, method: :get do %>
        <%= text_field_tag :q %>
      <br>
        <button class="btn waves-effect waves-light" type="submit" name="action">
            <%= submit_tag "search" %>
        </button>
      <% end %>

      <br>

      <h5> Results for <%= params[:q] || "Leonardo Di Caprio" %></h5>

      <ol>
        <% for movie in @movies %>
        <li>
          <%= image_tag movie[:artworkUrl100] %>
          <br>
          <%= movie[:trackName] %>
          <br>
          <a href="<%= movie[:trackViewUrl] %>" target="_blank">View In Itunes</a>
        </li>
        <br>
        <% end %>
      </ol>
    </div>
</div>

app/views/tracks/index.html.erb
<div class="section no-pad-bot" id="index-banner">
    <div class="container">
        <h4>10 Recent Songs - Search by Artist's Name</h4>

        <%= form_tag tracks_path, method: :get do %>
          <%= text_field_tag :q %>
        <br>
          <button class="btn waves-effect waves-light" type="submit" name="action">
            <%= submit_tag "search" %>
          </button>
        <% end %>

          <br>

        <h5> Results for <%= params[:q] || "Adele" %></h5>

        <ol>
          <% for track in @tracks %>
          <li>
            <%= image_tag track[:artworkUrl60] %>
            <br>
            <%= track[:trackName] %>
            <br>
            <a href="<%= track[:previewUrl] %>" target="_blank">Preview Song</a>
          </li>
          <br>
          <% end %>
        </ol>
    </div>
</div>